version: '3.7'

services:
  bb-db:
    image: ${dockerId}/bb-db:v3
    networks:
      - bb-net
    volumes:
      - sqlbackup:/var/lib/postgresql/data

  bb-app:
    image: ${dockerId}/bb-app:v3
    networks:
      - bb-net

  bb-proxy:
    image: ${dockerId}/bb-proxy:v3
    ports:
      - "8000:80"
    networks:
      - bb-net

networks:
  bb-net:

volumes:
  sqlbackup:
